"""SUPERSEDED 29 Sep 2026 — the launcher now comes from art/logo/make_launcher.py (owner artwork). Kept for history only."""
"""Generates art/miqaat-icon.svg (master), the Android adaptive-icon drawables and the PNG exports."""
import subprocess, os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
B = 58                      # arch band thickness
APEX = 246
L0, L1 = 120, 660           # left arch span
R0, R1 = 364, 904           # right arch span (overlap with the left forms the lit door)

def arch(x0, x1, apex_y, floor=930):
    xm = (x0 + x1) / 2
    return f"M{x0} {floor} V560 C{x0} 400 {xm-70} {apex_y+30} {xm} {apex_y} C{xm+70} {apex_y+30} {x1} 400 {x1} 560 V{floor} Z"

L_out, L_in = arch(L0, L1, APEX), arch(L0+B, L1-B, APEX+B*1.35)
R_out, R_in = arch(R0, R1, APEX), arch(R0+B, R1-B, APEX+B*1.35)
CRESCENT = dict(cx=492, cy=150, r=72, cx2=528, cy2=127, r2=64)

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <!-- Miqaat app icon · master. Generated by art/make_icon.py — edit the script, not this file. -->
  <defs>
    <radialGradient id="ground" cx="50%" cy="34%" r="78%"><stop offset="0" stop-color="#2C2566"/><stop offset="0.55" stop-color="#191B48"/><stop offset="1" stop-color="#0A0C28"/></radialGradient>
    <radialGradient id="glow" cx="50%" cy="66%" r="44%"><stop offset="0" stop-color="#FFB25A" stop-opacity="0.75"/><stop offset="0.55" stop-color="#E77E48" stop-opacity="0.25"/><stop offset="1" stop-color="#E77E48" stop-opacity="0"/></radialGradient>
    <linearGradient id="door" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#FFF1D6"/><stop offset="0.4" stop-color="#FFC77E"/><stop offset="1" stop-color="#F0873A"/></linearGradient>
    <linearGradient id="band" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#FBEBC6" stop-opacity="0.95"/><stop offset="0.5" stop-color="#E7C282" stop-opacity="0.9"/><stop offset="1" stop-color="#B8893C" stop-opacity="0.9"/></linearGradient>
    <linearGradient id="glass" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#FFFFFF" stop-opacity="0.16"/><stop offset="1" stop-color="#FFFFFF" stop-opacity="0.04"/></linearGradient>
    <linearGradient id="floor" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#F9B066" stop-opacity="0.95"/><stop offset="1" stop-color="#F9B066" stop-opacity="0.15"/></linearGradient>
    <linearGradient id="gold" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#FFEBB8"/><stop offset="1" stop-color="#D8A74A"/></linearGradient>
    <clipPath id="sq"><rect width="1024" height="1024" rx="228"/></clipPath>
    <clipPath id="leftIn"><path d="{L_in}"/></clipPath>
    <mask id="crescent"><rect width="1024" height="1024" fill="black"/><circle cx="{CRESCENT['cx']}" cy="{CRESCENT['cy']}" r="{CRESCENT['r']}" fill="white"/><circle cx="{CRESCENT['cx2']}" cy="{CRESCENT['cy2']}" r="{CRESCENT['r2']}" fill="black"/></mask>
  </defs>
  <g clip-path="url(#sq)">
    <rect width="1024" height="1024" fill="url(#ground)"/>
    <circle cx="512" cy="700" r="460" fill="url(#glow)"/>
    <path d="{L_in}" fill="url(#glass)"/><path d="{R_in}" fill="url(#glass)"/>
    <g clip-path="url(#leftIn)"><path d="{R_in}" fill="url(#door)"/></g>
    <path d="M{(L1-B+R0+B)/2-40} 930 L{(L1-B+R0+B)/2+40} 930 L740 1024 L284 1024 Z" fill="url(#floor)"/>
    <path d="{L_out} {L_in}" fill="url(#band)" fill-rule="evenodd"/>
    <path d="{R_out} {R_in}" fill="url(#band)" fill-rule="evenodd"/>
    <path d="{L_in}" fill="none" stroke="#FFF7E3" stroke-opacity="0.55" stroke-width="5"/>
    <path d="{R_in}" fill="none" stroke="#FFF7E3" stroke-opacity="0.55" stroke-width="5"/>
    <rect width="1024" height="1024" fill="url(#gold)" mask="url(#crescent)"/>
  </g>
</svg>'''
open('miqaat-icon.svg', 'w').write(svg)

# ---- Android adaptive icon (108 dp viewport; the visible safe circle is the centre 66 dp) ----
# Foreground content is scaled so the whole composition (1024 px master) sits inside the safe zone.
S = 0.78 * 108 / 1024
def tr(d):  # scale path numbers
    import re
    return re.sub(r'-?\d+(?:\.\d+)?', lambda m: f"{float(m.group())*S + (108 - 1024*S)/2:.2f}", d)
def circ(cx, cy, r):  # circle as path
    cx, cy, r = cx*S + (108-1024*S)/2, cy*S + (108-1024*S)/2, r*S
    return f"M{cx-r:.2f} {cy:.2f} a{r:.2f} {r:.2f} 0 1 0 {2*r:.2f} 0 a{r:.2f} {r:.2f} 0 1 0 {-2*r:.2f} 0 Z"
NS = 'xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt"'
def grad(y0, y1, stops, kind="linear", cx=54, cy=54, r=54):
    if kind == "linear":
        head = f'<gradient android:type="linear" android:startX="54" android:startY="{y0}" android:endX="54" android:endY="{y1}">'
    else:
        head = f'<gradient android:type="radial" android:centerX="{cx}" android:centerY="{cy}" android:gradientRadius="{r}">'
    return head + "".join(f'<item android:offset="{o}" android:color="{c}"/>' for o, c in stops) + '</gradient>'
def path(d, fill=None, gradient=None, fill_type="nonZero", stroke=None, sw=None, alpha=None):
    a = f' android:fillAlpha="{alpha}"' if alpha is not None else ''
    if gradient:
        return f'<path android:pathData="{d}" android:fillType="{fill_type}"{a}><aapt:attr name="android:fillColor">{gradient}</aapt:attr></path>'
    s = f' android:strokeColor="{stroke}" android:strokeWidth="{sw}"' if stroke else ''
    return f'<path android:pathData="{d}" android:fillColor="{fill or "#00000000"}" android:fillType="{fill_type}"{a}{s}/>'

y = lambda v: v*S + (108-1024*S)/2
bg = f'''<?xml version="1.0" encoding="utf-8"?>
<vector {NS} android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
    {path("M0 0h108v108H0z", gradient=grad(0,0,[("0","#FF2C2566"),("0.55","#FF191B48"),("1","#FF0A0C28")],"radial",54,40,90))}
    {path(circ(512,700,460), gradient=grad(0,0,[("0","#BFFFB25A"),("0.55","#40E77E48"),("1","#00E77E48")],"radial",y(512),y(700),460*S))}
</vector>'''
fg = f'''<?xml version="1.0" encoding="utf-8"?>
<vector {NS} android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
    {path(tr(L_in), fill="#FFFFFF", alpha="0.10")}
    {path(tr(R_in), fill="#FFFFFF", alpha="0.10")}
    <group>
    <clip-path android:pathData="{tr(L_in)}"/>
    {path(tr(R_in), gradient=grad(y(300), y(930), [("0","#FFFFF1D6"),("0.4","#FFFFC77E"),("1","#FFF0873A")]))}
    </group>
</vector>'''
# clip-path applies to following siblings in the same group; put the bands and crescent in a fresh group
fg = fg.replace('</vector>', f'''    <group>
    {path("M" + f"{y((L1-B+R0+B)/2-40):.2f} {y(930):.2f} L{y((L1-B+R0+B)/2+40):.2f} {y(930):.2f} L{y(740):.2f} {y(1024)+6:.2f} L{y(284):.2f} {y(1024)+6:.2f} Z", gradient=grad(y(930), y(1024), [("0","#F2F9B066"),("1","#26F9B066")]))}
    {path(tr(L_out) + " " + tr(L_in), gradient=grad(y(246), y(930), [("0","#F2FBEBC6"),("0.5","#E6E7C282"),("1","#E6B8893C")]), fill_type="evenOdd")}
    {path(tr(R_out) + " " + tr(R_in), gradient=grad(y(246), y(930), [("0","#F2FBEBC6"),("0.5","#E6E7C282"),("1","#E6B8893C")]), fill_type="evenOdd")}
    {path(tr(L_in), stroke="#8CFFF7E3", sw="0.4")}
    {path(tr(R_in), stroke="#8CFFF7E3", sw="0.4")}
    {path(circ(CRESCENT['cx'],CRESCENT['cy'],CRESCENT['r']) + " " + circ(CRESCENT['cx2'],CRESCENT['cy2'],CRESCENT['r2']), gradient=grad(y(80), y(220), [("0","#FFFFEBB8"),("1","#FFD8A74A")]), fill_type="evenOdd")}
    </group>
</vector>''')
mono = f'''<?xml version="1.0" encoding="utf-8"?>
<vector {NS} android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
    {path(tr(L_out) + " " + tr(L_in), fill="#FFFFFFFF", fill_type="evenOdd")}
    {path(tr(R_out) + " " + tr(R_in), fill="#FFFFFFFF", fill_type="evenOdd")}
    {path(circ(CRESCENT['cx'],CRESCENT['cy'],CRESCENT['r']) + " " + circ(CRESCENT['cx2'],CRESCENT['cy2'],CRESCENT['r2']), fill="#FFFFFFFF", fill_type="evenOdd")}
</vector>'''
res = '/home/claude/miqaat/app/src/main/res/'
open(res+'drawable/ic_launcher_background.xml','w').write(bg)
open(res+'drawable/ic_launcher_foreground.xml','w').write(fg)
open(res+'drawable/ic_launcher_monochrome.xml','w').write(mono)
open(res+'mipmap-anydpi-v26/ic_launcher.xml','w').write('''<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
''')
subprocess.run(['python3', 'render.py'], check=True)
print('done')
